# Generated by Django 2.1.5 on 2019-02-17 09:45


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('size', models.CharField(choices=[('S', 'Option S'), ('M', 'Option M'), ('L', 'Option L'), ('XL', 'Option XL'), ('XXL', 'Option XXL'), ('3XL', 'Option 3XL')], default=(('XL', 'Option 2'),), max_length=100)),
            ],
        ),
    ]
