# Generated by Django 2.1.5 on 2019-02-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Option 1'), ('M', 'Option 2'), ('L', 'Option 1'), ('XL', 'Option 2'), ('XXL', 'Option 1'), ('3XL', 'Option 2')], default=(('XL', 'Option 2'),), max_length=100),
        ),
    ]
