# Generated by Django 2.1.5 on 2019-02-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Option S'), ('M', 'Option M'), ('L', 'Option L'), ('XL', 'Option XL'), ('XXL', 'Option XXL'), ('3XL', 'Option 3XL')], default=(('XL', 'Option 2'),), max_length=100),
        ),
    ]
