# Generated by Django 2.1.5 on 2019-02-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190217_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Opis produktu', max_length=200),
        ),
    ]
